### ISSUE TITLE
POST features from UI (frontends)

### ISSUE THREAD

**Issue by JoeOsborn** [shftgroup/embedulator#10]
POSTing states, replays, maybe saves and instances too?

**Comment by ekaltman** [comment]
Are you thinking we want form entry for this or just to turn on the routes for POSTing things in a similar way to the objects? Figure extracting that code would not be too much of a lift.

**Comment by JoeOsborn** [comment]
I think we need user provided data, I’m imagining this is like “I made my states in the app and now I need to upload them”.  So, something in the gisst UI package mainly which maybe makes a callback to the frontend with the json to be posted.  Maybe this should be a couple separate issues?

**Comment by ekaltman** [comment]
We have the posts integrated now, closing this issue and we will be more specific on future api issues.
